### ISSUE TITLE
Multiple uploads

### ISSUE THREAD

**Issue by sniepoort** [founderlab/react-dropzone-s3-uploader#12]
I'm not quite sure how you've implemented multiple uploads? As far as I can tell, onFinish only get's called once, even if multiple images have been dragged into the component. So how do you handle that?
The react-dropzone component stores the files in state, where you then can loop through them onDrop

**Comment by anaumov** [comment]
How you solve this?

**Comment by sniepoort** [comment]
@anaumov, I didn't actually solve it. I realized this component just wasn't built well enough and dropped the idea of using it. 
However, I ended up making a manual mesh of dropzone and s3 which turned out great. I was guided by this thread on s3 uploader: https://github.com/odysseyscience/react-s3-uploader/issues/43

**Comment by anaumov** [comment]
@sniepoort thanks for sharing!
