### ISSUE TITLE
Multiple files preview

### ISSUE THREAD

**Issue by sniepoort** [founderlab/react-dropzone-s3-uploader#13]
How is the component supposed to handle displaying multiple files/images? If it only accepts ONE fileUrl, then what is the purpose of multiple file uploads?

**Comment by gwilymhumphreys** [comment]
Published v0.8.0, which should handle multiple files correctly. Let me know if I've missed anything. Props named `fileUrls` and `filenames` are passed to the `fileComponent`, with an entry per file uploaded.
