### ISSUE TITLE
Please Add onStart property

### ISSUE THREAD

**Issue by talbenbasat** [founderlab/react-dropzone-s3-uploader#17]
Hi @gwilymhumphreys ,

react-s3-uploader added a new feature that I really need - onStart.

Can you please add it to the component https://github.com/odysseyscience/react-s3-uploader/pull/79

Tal

**Comment by talbenbasat** [comment]
Maybe even allow other object style prop and pass it to the S3Upload

**Comment by talbenbasat** [comment]
Hi @gwilymhumphreys,
Any updates?

**Comment by gwilymhumphreys** [comment]
Hey - I've merged this PR from @Akronix: https://github.com/founderlab/react-dropzone-s3-uploader/pull/20. Will the `preprocess` prop do what you're after? I've also added another prop, `uploaderOptions`, so you can pass anything else needed to the react-s3-uploader uploader instance.
That's released now, v0.9.0.
The dependency on `react-dropzone-s3-uploader` has been updated to v3.3.0 too - seems ok on my end, let me know if there's any problems.

**Comment by talbenbasat** [comment]
@gwilymhumphreys  Thanks a lot,
I appreciate it.

I'll let you know if it works
