### ISSUE TITLE
image orientation from iOS

### ISSUE THREAD

**Issue by silvestri** [founderlab/react-dropzone-s3-uploader#22]
Not sure if this is an issue with the uploader or not but when i take a picture in portrait mode from iOS and upload it with react-dropzone-s3-uploader it appears at a 90° angle when i go to view the image. Images taken in landscape mode are fine. Some preliminary research has me thinking it might have something to do with the exif info but I'm not sure if there is a way to set that info with the uploader or not. Pictures pulled from the camera roll seem to be fine. If anyone has seen this and has info great, otherwise you can close this issue. Thanks!

**Comment by gwilymhumphreys** [comment]
Hey - that's right, it'll likely have the orientation exif tag set. Browsers should handle it just fine though. Where are you displaying it? 

I tried this (safari, ios): 
- Click my uploader and take a photo as portrait -> photo is rendered in the browser correctly
- Click my uploader and take a photo as landscape -> photo is rendered in the browser correctly

So I'm wondering if it's a problem with the orientation being ignored when you're displaying the image - is it in an app or somesuch?

**Comment by silvestri** [comment]
yes, it's a node app using react.js on the front end. I've actually seen this issue on a another project but a different engineer was assigned the bug.

**Comment by gwilymhumphreys** [comment]
Manage to find / fix the problem?
