### ISSUE TITLE
Client custom headers

### ISSUE THREAD

**Issue by estebanbouza** [founderlab/react-dropzone-s3-uploader#23]
Unless I'm missing something, it doesn't seem possible to add custom headers to the signing servers. How could I request a signing URL to my server using an authorization header?

**Comment by gwilymhumphreys** [comment]
The `signingUrlHeaders` prop is passed through as-is to `react-s3-uploader` (used in the initial request to your server for the signed url).
The `headers` prop is passed as `uploadRequestHeaders` to `react-s3-uploader` (used in the upload request to s3). This should probably be renamed to `uploadRequestHeaders`, I don't know why it's different tbh.
