### ISSUE TITLE
Removing previews

### ISSUE THREAD

**Issue by estebanbouza** [founderlab/react-dropzone-s3-uploader#26]
Currently I don't see how it would be possible to let the user remove an item once it has been dragged into the dropzone area.

Dropzone supports `addRemoveLinks`. Any hint on how this could be used from react-dropzone-s3-uploader?

**Comment by anaumov** [comment]
hey @estebanbouza, you can remove file once it uploaded. Just remove it from array of files. Is it desired behaviour?

**Comment by estebanbouza** [comment]
Hi @anaumov. How would it be possible to delete arbitrary previews? Removing from an array is ok, but what about the UI?

Currently what I've done is to add a "trash" button on top of each preview. The problem is that I either `disableClick: true` to receive click events on the button, or I `disableClick: false` so that a user on mobile can tap the dropzone to select a photo. I can't have both at the same time.

However on Dropzone they seem to have this functionality already built in:
https://github.com/enyo/dropzone/wiki/FAQ#how-to-add-a-button-to-remove-each-file-preview

Do you have any clue how it could be accessed from react-dropzone-s3-uploader ?
<img width="835" alt="screen shot 2017-03-09 at 19 41 00" src="https://cloud.githubusercontent.com/assets/1743753/23750611/5c319bb6-0500-11e7-95dc-3aed3f52e5b8.png">

**Comment by anaumov** [comment]
Hi @estebanbouza! I think you have to enable click for dropzone component on mobile. Just when user clicks on 'trash' btn you have to prevent its propagation.
```javascript
var removeImage = function(event) {
  event.stopPropagation();
  var randomIndex = Math.floor(Math.random() * (imagesList.length + 1));
  imagesList.splice(randomIndex, 1);
}


<a onClick={removeImage}>Remove image</a>
```
