### ISSUE TITLE
Props for custom component

### ISSUE THREAD

**Issue by barmalejj** [founderlab/react-dropzone-s3-uploader#27]
In your README is written: *Specify your own display for an uploaded file. Will receive these props: {fileUrl, s3Url, filename, progress, error, imageStyle}*, but it never does. Check your code, `childProps` are passed only to `FileComponent` (which is not documented at all). These values are never passed to `DropzoneS3Uploader` children.

**Comment by gwilymhumphreys** [comment]
That's correct, the docs were out of date.
