### ISSUE TITLE
Several props are deprecated in 'react-dropzone'.

### ISSUE THREAD

**Issue by anaumov** [founderlab/react-dropzone-s3-uploader#28]
Props are deprecated in 'react-dropzone': style, activeStyle, rejectStyle, className, activeClassName, rejectClassName, maxSize, minSize.

https://github.com/okonet/react-dropzone/commit/0cc351dfb63dde40561b19c06c455d2172c8eaea

https://github.com/founderlab/react-dropzone-s3-uploader/blob/a7c15d5921769d232de1becefece958706772fe3/src/DropzoneS3Uploader.js#L142

**Comment by gwilymhumphreys** [comment]
Cheers - manually passing these props through has been a bit of a pain.
I'm thinking that, in the next version, props for `react-dropzone` can be be provided as a single object via a prop named `dropzoneProps`.

**Comment by anaumov** [comment]
Yeah, I think it's nice and obvious solution.

**Comment by gwilymhumphreys** [comment]
Hey, I ended up going the opposite route - all props not used here are passed to `react-dropzone`.

Should be good in the latest release. They've removed the deprecation warnings for now as well I believe.
