### ISSUE TITLE
Custom progress component

### ISSUE THREAD

**Issue by ilyakatz** [founderlab/react-dropzone-s3-uploader#3]
It would be great if there was a way to pass in custom progress element. Currently, I would need to require the full `react-bootstrap` just to get a progress bar

**Comment by gwilymhumphreys** [comment]
Yeah agreed, no need for that dependency. Will update shortly.

**Comment by gwilymhumphreys** [comment]
Fixed that up with 0.7.0. [See the changes here](https://github.com/founderlab/react-dropzone-s3-uploader/blob/master/changelog.md).

**Comment by ilyakatz** [comment]
Nice, thank you @gwilymhumphreys. Could you help me a bit (pretty new to react), so how can I use the new property if I want to use https://github.com/react-component/progress

I know this is wrong but how could I do something like this

``` javascript
<DropzoneS3Uploader
    onFinish={this.onUploadFinish}
    max_file_size = { 1024 * 1024 * 50 }
    progressComponent = {<Line percent={this.props.progress}/>} 
    signing_url_query_params =  {{asset_id: this.props.assetId}}
/>
```

Thanks in advance!

**Comment by gwilymhumphreys** [comment]
You can pass it a pure function component that renders the progress bar like so (this is what I am doing now)

``` javascript
// somewhere else, can be a class method or whatever
renderProgressBar(props)  {
  return (<Line percent={props.progress} />)
}

// down in your render method
<DropzoneS3Uploader
    ...
    progressComponent={renderProgressBar} 
/>

```

**Comment by ilyakatz** [comment]
cool, thank you!

**Comment by LawJolla** [comment]
Along the same lines, how would you clear the progressComponent onError?  It clears after onFinish, but it doesn't unmount onError.

Thanks for your great work!

**Comment by gwilymhumphreys** [comment]
Good point, most of the time there won't be any need for progress if it errors. v0.7.2 clears the progress in the same way as onFinish (see 9ea90f0).
