### ISSUE TITLE
Undefined filename in the fileUrl returned on handleFinish

### ISSUE THREAD

**Issue by zavrick** [founderlab/react-dropzone-s3-uploader#33]
`info.filename` is passed into fileUrl which is undefined.
I think it should be `info.file.name`
does this have to do with the S3-uploader versions?

**Comment by gwilymhumphreys** [comment]
Thanks for the heads up (and sorry for the delayed response). Looks like `react-s3-uploader` was changing things internally between versions, which is fair enough but may have caused some probs with the filename. I've locked the version to 4.5.0 so we should be alright now.

**Comment by summera** [comment]
@gwilymhumphreys still seeing this issue in `1.1.0`

**Comment by subhamagr** [comment]
Same here. I am receiving `fileUrl: "https://test-bucket.s3.amazonaws.com/undefined"`
version: 1.1.0

**Comment by stasb** [comment]
I am getting the same problem. What's the fix?

**Comment by summera** [comment]
@stasb I ended up creating my own s3 uploader with Dropzone using this as inspiration. I also replaced `react-s3-uploader` with [fine-uploader](https://github.com/FineUploader/fine-uploader) which is more robust and has support for chunked uploads. It's worked well for us.
