### ISSUE TITLE
Invalid Response From Server

### ISSUE THREAD

**Issue by AntoniAngga** [founderlab/react-dropzone-s3-uploader#45]
Hello,
can you help me, i have problem when i use react-dropzone-s3-uploader.
i upload my photo, and i got Message "Invalid Response From Server", why ?

```javascript
const uploadOptions = {
            server: 'http://localhost:3000',
            signingUrlQueryParams: { uploadType: 'avatar' },
        }

const s3Url = 'https://hi.s3.amazonaws.com/' // i think Url like that( because i confuse to find url S3).

return (
<DropzoneS3Uploader
    onFinish={this.handleFinishedUpload}
    s3Url={s3Url}
    maxSize={1024 * 1024 * 5}
    upload={uploadOptions}
/>
)
```

**Comment by tmf-chris** [comment]
When you want to know what to put for s3Url you should look in s3 when you are viewing your bucket, the url would look like this:

`https://s3.console.aws.amazon.com/s3/buckets/<mybucket>/?region=us-west-1&tab=overview`

Therefore my s3Url is:

`https://s3.us-west-1.amazonaws.com/<mybucket>/`

**Comment by cleandersonlobo** [comment]
I have the same problem. Did you find any solutions?
