### ISSUE TITLE
How do I explicitly pass the AWS Access Key Id?

### ISSUE THREAD

**Issue by matthewfbenjamin** [founderlab/react-dropzone-s3-uploader#50]
I am using an express server.
```
app.use('/s3', require('react-dropzone-s3-uploader/s3router')({
  bucket: my-s3-bucket',
  region: 'us-east-1',
  headers: { 'Access-Control-Allow-Origin': '*' },
  ACL: 'public-read',
}))
```

The issue is that the url is missing the AWSAccessKeyId query parameter (see below)

https://s3.amazonaws.com/my-s3-bucket/fjdshjsklfhsadhfdshf_spiderman.jpg?AWSAccessKeyId=&Content-Type=image%2Fjpeg&Expires=1516309866&Signature=&x-amz-acl=public-read

I have this listed in my `.env` file

```
REACT_APP_AWS_ACCESS_KEY_ID="ABUNCHOFLETTERS"
REACT_APP_AWS_SECRET_ACCESS_KEY="ABUNCHOFLETTERSANDNUMBERS12345"
AWS_ACCESS_KEY_ID="ABUNCHOFLETTERS"
AWS_SECRET_ACCESS_KEY="ABUNCHOFLETTERSANDNUMBERS12345"
```

Does anyone have any suggestions?

**Comment by fishdag** [comment]
any help with this?
i have a react app with webpack, don;t understand how do i set my server...

**Comment by matthewfbenjamin** [comment]
My issue was the `REACT_APP_AWS_SECRET_KEY_ID` had to be `AWS_SECRET_ACCESS_KEY` and  `REACT_APP_AWS_ACCESS_KEY_ID` had to be `AWS_ACCESS_KEY_ID`

**Comment by fishdag** [comment]
@mbenjamin618 
i need some help, 
I have a react app with a webpack server which is supposed to upload files to s3.
i don't understand how to configure the server part with webpack, since im not using express.. i cant use the given example for server usage in the readme.

do you have any advice please?
